name: Exemplo Github Actions

on:
  workflow_dispatch:
jobs:
  acao_inicial_job:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir OLA
        run: echo "OLA"
      - name: Imprimir TCHAU
        run: echo "TCHAU"
    
